version: '3.8'
services:
  web:
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
      - FLASK_DEBUG=1
    command: python -m flask run --host=0.0.0.0 --port=8000
    
  mongo:
    ports:
      - "27017:27017"
